"""add_project_categories_and_task_templates

Revision ID: a17ba592b4e8
Revises: 23044d664992
Create Date: 2026-06-15 20:31:15.511670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17ba592b4e8'
down_revision = '23044d664992'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_categories_name'), 'project_categories', ['name'], unique=True)
    op.create_table('task_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['project_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_templates_category_id'), 'task_templates', ['category_id'], unique=False)
    op.create_table('task_template_usages',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'template_id')
    )
    op.create_index(op.f('ix_task_template_usages_template_id'), 'task_template_usages', ['template_id'], unique=False)
    op.create_index(op.f('ix_task_template_usages_user_id'), 'task_template_usages', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('category_id', sa.Uuid(), nullable=True))
    
    # Custom Data Migration: Insert default "General" category and update existing projects
    import uuid
    from datetime import datetime, timezone
    general_uuid = uuid.uuid4()
    
    categories_table = sa.table(
        'project_categories',
        sa.column('id', sa.Uuid),
        sa.column('name', sa.String),
        sa.column('description', sa.Text),
        sa.column('created_at', sa.DateTime)
    )
    op.bulk_insert(categories_table, [
        {
            'id': general_uuid,
            'name': 'General',
            'description': 'Default category for General',
            'created_at': datetime.now(timezone.utc)
        }
    ])
    
    projects_table = sa.table(
        'projects',
        sa.column('category_id', sa.Uuid)
    )
    op.execute(
        projects_table.update().values(category_id=general_uuid)
    )
    
    op.create_foreign_key(None, 'projects', 'project_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'category_id')
    op.drop_index(op.f('ix_task_template_usages_user_id'), table_name='task_template_usages')
    op.drop_index(op.f('ix_task_template_usages_template_id'), table_name='task_template_usages')
    op.drop_table('task_template_usages')
    op.drop_index(op.f('ix_task_templates_category_id'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_project_categories_name'), table_name='project_categories')
    op.drop_table('project_categories')
    # ### end Alembic commands ###
